HotelBookingManagerWeb/src/main/java/cz/fi/muni/pa165/hotelbookingmanagerweb/UsersActionBean.java
package cz.fi.muni.pa165.hotelbookingmanagerweb;

import cz.fi.muni.pa165.hotelbookingmanagerapi.service.RegUserService;
import cz.fi.muni.pa165.hotelbookingmanagerapi.transferobjects.RegUserTO;
import java.util.Set;
import javax.ws.rs.WebApplicationException;
import javax.ws.rs.core.Response;
import net.sourceforge.stripes.action.*;
import net.sourceforge.stripes.controller.LifecycleStage;
import net.sourceforge.stripes.integration.spring.SpringBean;
import net.sourceforge.stripes.validation.LocalizableError;
import net.sourceforge.stripes.validation.Validate;
import net.sourceforge.stripes.validation.ValidateNestedProperties;
import net.sourceforge.stripes.validation.ValidationErrors;
import org.springframework.dao.DataAccessException;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;

/**
 *
 * @author Andrej Galád
 */
@UrlBinding("/users/{$event}/{user.id}")
public class UsersActionBean implements ActionBean {
 
    private ActionBeanContext context;
    
    @ValidateNestedProperties(value = {
            @Validate(on = {"add"}, field = "username", required = true, minlength = 2, maxlength = 30),
			@Validate(on = {"save"}, field = "password", minlength = 2, maxlength = 30),
            @Validate(on = {"add"}, field = "password", required = true, minlength = 2, maxlength = 30),
            @Validate(on = {"add", "save"}, field = "client.firstName", required = true, minlength = 2, maxlength = 50),
            @Validate(on = {"add", "save"}, field = "client.lastName", required = true, minlength = 2, maxlength = 50),
            @Validate(on = {"add", "save"}, field = "client.contact.phone", required = true, mask = "\\d*", maxlength = 30),
            @Validate(on = {"add", "save"}, field = "client.contact.email", required = true, mask = "[\\w\\-\\.\\+]+@[a-zA-Z0-9\\.\\-]+\\.[a-zA-z]+", minlength = 6, maxlength = 50),
            @Validate(on = {"add", "save"}, field = "client.contact.address", required = true, maxlength = 30),
            @Validate(on = {"add", "save"}, field = "client.contact.city", required = true, minlength = 2, maxlength = 50)
    })
    private RegUserTO user;
    
    public RegUserTO getLogged() {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        String username = auth.getName();
        return userService.findUserByUsername(username);
    }

    public RegUserTO getUser() {
        return user;
    }

    public void setUser(RegUserTO user) {
        this.user = user;
    }
    
    @SpringBean
    private RegUserService userService;
    
    private CountryPicker countryPicker = new CountryPicker();

    public Set<String> getCountries() {
        return countryPicker.getCountriesName();
    }
    
    @Override
    public void setContext(ActionBeanContext context) {
        this.context = context;
    }

    @Override
    public ActionBeanContext getContext() {
        return context;
    }
    
    @DefaultHandler
    public Resolution userDetails() {
        return new ForwardResolution("/users/user.jsp");
    }
    
    public Resolution register() {
        return new ForwardResolution("/register.jsp");
    }
    
    public Resolution add() {
        try {
            userService.create(user);
            return new RedirectResolution("/index.jsp");
        } catch (DataAccessException e) {
            ValidationErrors errors = new ValidationErrors();
            errors.add( "user.username", new LocalizableError("validation.user.nameIsExisting") );
            getContext().setValidationErrors(errors);
            return getContext().getSourcePageResolution();
        }
    }
    
    @Before(stages = LifecycleStage.BindingAndValidation, on = {"edit"})
    public void loadUserFromDatabase() {
        String ids = context.getRequest().getParameter("user.id");
        if (ids == null) {
            return;
        }
		Long id = Long.parseLong(ids);
		if (!getLogged().getId().equals(id)) {
			throw new WebApplicationException(Response.Status.FORBIDDEN);
		}
        user = userService.get(id);
    }

    public Resolution edit() {
        return new ForwardResolution("/users/editUser.jsp");
    }

    public Resolution save() {
        String ids = context.getRequest().getParameter("user.id");
        if (ids == null) {
            return new RedirectResolution(this.getClass(), "details");
        }
		Long id = Long.parseLong(ids);
		if (!getLogged().getId().equals(id)) {
			throw new WebApplicationException(Response.Status.FORBIDDEN);
		}
        RegUserTO userTmp = userService.get(id);
        user.setUsername(userTmp.getUsername());
        if (user.getPassword() == null) {
                user.setPassword(userTmp.getPassword());
        }
        user.getClient().setId(userTmp.getClient().getId());
		
        userService.update(user);
        return new RedirectResolution(this.getClass(), "details");
    }
}

HotelBookingManagerWeb/src/main/webapp/users/editUser.jsp
<%-- 
    Document   : editUser
    Created on : Jan 19, 2013, 8:53:19 PM
    Author     : Andrej Galád
--%>

<%@ page contentType="text/html; charset=utf-8" pageEncoding="utf-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>

<fmt:message var="pageTitle" key="user.pageTitle"/>
<s:layout-render name="/layout.jsp" title= "${pageTitle}" pageInfo="user.jsp">
    <s:layout-component name="right_content">
       <s:useActionBean beanclass="cz.fi.muni.pa165.hotelbookingmanagerweb.UsersActionBean" var="actionBean"/>

            <div class="content_right_section">
                <div class="content_title_02"><fmt:message key="changeUser"/></div>
                <p><fmt:message key="changeUserDescription"/></p>

                <div class="cleaner">&nbsp;</div>
            </div>

            <div class="cleaner_h40">&nbsp;</div>

            <s:form beanclass="cz.fi.muni.pa165.hotelbookingmanagerweb.UsersActionBean" action="/users/save/">
                <div class="content_right_section">
                    <div class="content_title_03"><fmt:message key="attributesUser"/> ${actionBean.user.username}: </div>

                        <s:hidden name="user.id"/>
                        <%@include file="formUser.jsp"%>
                        <div class="cleaner_h20">&nbsp;</div>

                    <div class="cleaner">&nbsp;</div>
                </div> <!-- end of editing -->

                <div class="content_right_2column_box">
                    <s:submit name="save"/>
                    <div class="cleaner_h10">&nbsp;</div>
                </div>

                <div class="content_right_2column_box">
                    <div class="rc_btn_02"/><s:link href="/users/userDetails/"><fmt:message key="userDetails"/></s:link></div>
                    <div class="cleaner_h10">&nbsp;</div>
                </div>
            </s:form>

    </s:layout-component>
</s:layout-render>

HotelBookingManagerWeb/src/main/webapp/users/formUser.jsp
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>

<s:errors/>
<div class="content_title_04"><fmt:message key="primaryDetails"/></div>
<sec:authorize access="isAnonymous()">
<div class="form_row">
        <s:label for="b1" name="user.username"/>
        <s:text id="b1" name="user.username"/>
</div>
</sec:authorize>
<div class="form_row">
        <s:label for="b2" name="user.password"/>
        <s:password id="b2" name="user.password"/>
</div>

<div class="cleaner_h30">&nbsp;</div>

<div class="content_title_04"><fmt:message key="secondaryDetails"/></div>
<div class="form_row">
        <s:label for="b3" name="client.firstName"/>
        <s:text id="b3" name="user.client.firstName"/>
</div>
<div class="form_row">
        <s:label for="b4" name="client.lastName"/>
        <s:text id="b4" name="user.client.lastName"/>
</div>
<div class="form_row">
        <s:label for="b5" name="client.phone"/>
        <s:text id="b5" name="user.client.contact.phone"/>
</div>
<div class="form_row">
        <s:label for="b6" name="client.email"/>
        <s:text id="b6" name="user.client.contact.email"/>
</div>
<div class="form_row">
        <s:label for="b7" name="client.address"/>
        <s:text id="b7" name="user.client.contact.address"/>
</div>
<div class="form_row">
        <s:label for="b8" name="client.city"/>
        <s:text id="b8" name="user.client.contact.city"/>
</div>
<div class="form_row">
        <s:label for="b9" name="client.country"/>
        <s:select name="user.client.contact.country">
                <s:options-collection collection="${actionBean.countries}" style="width:20px;" />
            </s:select>
</div>

HotelBookingManagerWeb/src/main/webapp/users/user.jsp
<%@ page contentType="text/html; charset=utf-8" pageEncoding="utf-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>

<fmt:message var="pageTitle" key="user.pageTitle"/>
<s:layout-render name="/layout.jsp" title="${pageTitle}" pageInfo="user.jsp">

    <s:layout-component name="right_content">
        <s:useActionBean beanclass="cz.fi.muni.pa165.hotelbookingmanagerweb.UsersActionBean" var="actionBean"/>

            <div class="content_right_section">
                    <div class="content_title_01"><fmt:message key="userManagement"/></div>
                    <img src="${pageContext.request.contextPath}/images/templatemo_image_04.jpg" alt="image" />
                    <fmt:message key="userManagementDescription"/>
                </div>

                <div class="cleaner_h40">&nbsp;</div>


                <div class="content_right_section">
                    <div class="content_title_02"><fmt:message key="userInfo"/></div>
                        <c:set var="user" value="${actionBean.logged}" />
                        </div>
                        
                        <div class="content_right_2column_box details_header">
                            <fmt:message key="user.userName"/>:
                        </div>
                        <div class="content_right_2column_box">
                            <c:out value="${user.username}" />
                        </div>
                        <div class="cleaner_h20">&nbsp;</div>
                        
                        <div class="cleaner_horizontal_divider_01">&nbsp;</div>
                        <div class="cleaner_h20">&nbsp;</div>
                            
                        <div class="content_right_2column_box details_header">
                            <fmt:message key="client.firstName"/>:
                        </div>
                        <div class="content_right_2column_box">
                            <c:out value="${user.client.firstName}" />
                        </div>
                        <div class="cleaner_h20">&nbsp;</div>
                        
                        <div class="content_right_2column_box details_header">
                            <fmt:message key="client.lastName"/>:
                        </div>
                        <div class="content_right_2column_box">
                            <c:out value="${user.client.lastName}" />
                        </div>
                        <div class="cleaner_h20">&nbsp;</div>
                        
                        <div class="content_right_2column_box details_header">
                            <fmt:message key="client.phone"/>:
                        </div>
                        <div class="content_right_2column_box">
                            <c:out value="${user.client.contact.phone}" />
                        </div>
                        <div class="cleaner_h20">&nbsp;</div>
                        
                        <div class="content_right_2column_box details_header">
                            <fmt:message key="client.email"/>:
                        </div>
                        <div class="content_right_2column_box">
                            <c:out value="${user.client.contact.email}" />
                        </div>
                        <div class="cleaner_h20">&nbsp;</div>
                        
                        <div class="content_right_2column_box details_header">
                            <fmt:message key="client.address"/>:
                        </div>
                        <div class="content_right_2column_box">
                            <c:out value="${user.client.contact.address}" />
                        </div>
                        <div class="cleaner_h20">&nbsp;</div>
                        
                        <div class="content_right_2column_box details_header">
                            <fmt:message key="client.city"/>:
                        </div>
                        <div class="content_right_2column_box">
                            <c:out value="${user.client.contact.city}" />
                        </div>
                        <div class="cleaner_h20">&nbsp;</div>
                        
                        <div class="content_right_2column_box details_header">
                            <fmt:message key="client.country"/>:
                        </div>
                        <div class="content_right_2column_box">
                            <c:out value="${user.client.contact.country}" />
                        </div>
                        <div class="cleaner_h20">&nbsp;</div>
                        
                        <div class="cleaner_horizontal_divider_01">&nbsp;</div>
                        <div class="cleaner_h20">&nbsp;</div>
                        
                        <div class="rc_btn_02"><s:link beanclass="cz.fi.muni.pa165.hotelbookingmanagerweb.UsersActionBean" event="edit"><s:param name="user.id" value="${user.id}"/><fmt:message key="edit"/></s:link></div>
                       
    </s:layout-component>
</s:layout-render>