HotelBookingManagerWeb/src/main/java/cz/fi/muni/pa165/hotelbookingmanagerweb/ReservationsActionBean.java
package cz.fi.muni.pa165.hotelbookingmanagerweb;

import cz.fi.muni.pa165.hotelbookingmanagerapi.service.*;
import cz.fi.muni.pa165.hotelbookingmanagerapi.transferobjects.*;
import java.text.DateFormat;
import java.text.DateFormatSymbols;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sourceforge.stripes.action.*;
import net.sourceforge.stripes.controller.LifecycleStage;
import net.sourceforge.stripes.integration.spring.SpringBean;
import net.sourceforge.stripes.validation.*;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;

/**
 *
 * @author Marian Rusnak
 */
@UrlBinding("/reservations/{$event}/{reservation.id}")
public class ReservationsActionBean implements ActionBean {

	private ActionBeanContext context;
	
	// service
	@SpringBean
	private ReservationService reservationService;
	@SpringBean
	private HotelService hotelService;
	@SpringBean
	private ClientService clientService;
	@SpringBean
	private RoomService roomService;
        @SpringBean
        private RegUserService userService;
	
	// DTO
	private ReservationTO reservation;
	@ValidateNestedProperties(value = {
		@Validate(on = "add", field = "id", required = true)
	})
	private ClientTO client;
	@ValidateNestedProperties(value = {
		@Validate(on = "add", field = "id", required = true)
	})
	private RoomTO room;
	@ValidateNestedProperties(value = {
		@Validate(on = {"createContinue", "add"}, field = "id", required = true)
	})
	private HotelTO hotel;
	
	// hepler fields
	private String months;
	private List<ReservationTO> reservations;
	private DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
	@Validate(on = {"createContinue", "add"}, required = true)
	private String from;
	@Validate(on = {"createContinue", "add"}, required = true)
	private String to;
	private Date dateFrom;
	private Date dateTo;

	@ValidationMethod(on = {"createContinue", "add"})
	public void validateFutureDates(ValidationErrors errors) {
		dateFrom = getDateFrom();
		dateTo = getDateTo();
		if (dateFrom == null || dateTo == null) {
			return;
		}
		if (dateFrom.before(new Date())) {
			errors.add("dateFrom", new LocalizableError("validation.date.future"));
		}
		if (dateTo.before(new Date())) {
			errors.add("dateTo", new LocalizableError("validation.date.future"));
		}
	}

	@ValidationMethod()
	public void validateDates(ValidationErrors errors) {
		dateFrom = getDateFrom();
		dateTo = getDateTo();
		if (dateFrom == null || dateTo == null) {
			return;
		}
		if (dateFrom.after(dateTo)) {
			errors.add("dates", new LocalizableError("validation.date.after"));
		}
	}

	public String getFrom() {
		return from;
	}

	public void setFrom(String from) {
		this.from = from;
	}

	public String getTo() {
		return to;
	}

	public void setTo(String to) {
		this.to = to;
	}

	public HotelTO getHotel() {
		return hotel;
	}

	public void setHotel(HotelTO hotel) {
		this.hotel = hotel;
	}

	public List<HotelTO> getHotels() {
		return hotelService.findAllHotels();
	}

	public List<ClientTO> getClients() {
		return clientService.findAllClients();
	}

	public List<RoomTO> getRooms() {
		return roomService.findVacantRooms(getDateFrom(), getDateTo(), hotel);
	}

	public String getMonths() {
		return months;
	}

	public void setMonths(String months) {
		this.months = months;
	}
	
	public List<ReservationTO> getReservations() {
		return reservations;
	}

	public void setReservations(List<ReservationTO> reservations) {
		this.reservations = reservations;
	}

	public ReservationTO getReservation() {
		return reservation;
	}

	public void setReservation(ReservationTO reservation) {
		this.reservation = reservation;
	}

	public ClientTO getClient() {
		return client;
	}

	public void setClient(ClientTO client) {
		this.client = client;
	}

	public RoomTO getRoom() {
		return room;
	}

	public void setRoom(RoomTO room) {
		this.room = room;
	}

	@Override
	public void setContext(ActionBeanContext context) {
		this.context = context;
	}

	@Override
	public ActionBeanContext getContext() {
		return context;
	}

	@Before(stages = LifecycleStage.ResolutionExecution)
	public void populateMonths() {
		String[] monthNames = (new DateFormatSymbols()).getMonths();
		StringBuilder months = new StringBuilder("[ ");
		for (int i = 0; i < 11; i++) {
			months.append('\'').append(monthNames[i]).append("', ");
		}
		months.append('\'').append(monthNames[11]).append("' ]");
		this.months = months.toString();
	}
	
	@DefaultHandler
	public Resolution all() {
            RegUserTO user = getLoggedUser();
            if (user == null) {
		if (from != null && !from.equals("") && to != null && !to.equals("")) {
			String hotelID = context.getRequest().getParameter("hotel.id");
			HotelTO hotel = null;
			if (hotelID != null) {
				hotel = hotelService.findHotel(Long.parseLong(hotelID));
			}
			if (hotel != null) {
				reservations = reservationService.findReservationsByDate(getDateFrom(), getDateTo(), hotel);
			} else {
				reservations = reservationService.findReservationsByDate(getDateFrom(), getDateTo());
			}
		} else {
			reservations = reservationService.findAllReservations();
		}
            } else {
                reservations = reservationService.findReservationsByClient(user.getClient());
            }

            return new ForwardResolution("/reservation/reservation.jsp");
	}

	private Date getDateFrom() {
		if (dateFrom != null) {
			return dateFrom;
		}
		try {
			from = context.getRequest().getParameter("from");
			if (from == null) {
				return null;
			}
			dateFrom = dateFormat.parse(from);
			return dateFrom;
		} catch (ParseException ex) {
			Logger.getLogger(ReservationsActionBean.class.getName()).log(Level.SEVERE, null, ex);
		}
		return null;
	}

	private Date getDateTo() {
		if (dateTo != null) {
			return dateTo;
		}
		try {
			to = context.getRequest().getParameter("to");
			if (to == null) {
				return null;
			}
			dateTo = dateFormat.parse(to);
			return dateTo;
		} catch (ParseException ex) {
			Logger.getLogger(ReservationsActionBean.class.getName()).log(Level.SEVERE, null, ex);
		}
		return null;
	}

	public Resolution chooseDate() {
		return new RedirectResolution(this.getClass(), "all");
	}

	public Resolution create() {
		return new ForwardResolution("/reservation/createStepOne.jsp");
	}

	@Before(stages = LifecycleStage.BindingAndValidation, on = {"createContinue", "add"})
	public void loadHotelFromDatabase() {
		String hotelID = context.getRequest().getParameter("hotel.id");
		if (hotelID == null) {
			return;
		}
		hotel = hotelService.findHotel(Long.parseLong(hotelID));
                RegUserTO user = getLoggedUser();
                if (user != null) {
                    client = user.getClient();
                }
	}

	public Resolution createContinue() {
		return new ForwardResolution("/reservation/createStepTwo.jsp");
	}
        
        public Resolution goBack() {
                return create();
        }

	@Before(stages = LifecycleStage.BindingAndValidation, on = {"add"})
	public void loadClientAndRoomFromDatabase() {
                RegUserTO user = getLoggedUser();
                if (user == null) {
                    String clientID = context.getRequest().getParameter("client.id");
                    if (clientID == null)
                        return;
                    client = clientService.findClient(Long.parseLong(clientID));
                } else {
                    client = user.getClient();
                }
		String roomID = context.getRequest().getParameter("room.id");
		dateFrom = getDateFrom();
		dateTo = getDateTo();
		if (roomID == null || dateFrom == null || dateTo == null) {
			return;
                }
		room = roomService.getRoom(Long.parseLong(roomID));

		reservation = new ReservationTO();
		reservation.setFromDate(dateFrom);
		reservation.setToDate(dateTo);
		reservation.setClient(client);
		reservation.setRoom(room);
		reservation.setPrice(room.getPricePerNight());
	}

	public Resolution add() {
		reservationService.createReservation(reservation);
		return new RedirectResolution(this.getClass(), "all");
	}

	@Before(stages = LifecycleStage.BindingAndValidation, on = {"delete"})
	public void loadReservationFromDatabase() {
		String ids = context.getRequest().getParameter("reservation.id");
		if (ids == null) {
			return;
		}
		reservation = reservationService.getReservation(Long.parseLong(ids));
	}

	public Resolution delete() {
		reservationService.deleteReservation(reservation);
		return new RedirectResolution(this.getClass(), "all");
	}
        
        private RegUserTO getLoggedUser() {
            Authentication auth = SecurityContextHolder.getContext().getAuthentication();
            for (GrantedAuthority authority : auth.getAuthorities()) {
                if (authority.getAuthority().equals("ROLE_ADMIN"))
                    return null;
            }
            String username = auth.getName();
            return userService.findUserByUsername(username);
        }
}

HotelBookingManagerWeb/src/main/java/cz/fi/muni/pa165/hotelbookingmanagerweb/UsersActionBean.java
package cz.fi.muni.pa165.hotelbookingmanagerweb;

import cz.fi.muni.pa165.hotelbookingmanagerapi.service.RegUserService;
import cz.fi.muni.pa165.hotelbookingmanagerapi.transferobjects.RegUserTO;
import java.util.Set;
import javax.ws.rs.WebApplicationException;
import javax.ws.rs.core.Response;
import net.sourceforge.stripes.action.*;
import net.sourceforge.stripes.controller.LifecycleStage;
import net.sourceforge.stripes.integration.spring.SpringBean;
import net.sourceforge.stripes.validation.LocalizableError;
import net.sourceforge.stripes.validation.Validate;
import net.sourceforge.stripes.validation.ValidateNestedProperties;
import net.sourceforge.stripes.validation.ValidationErrors;
import org.springframework.dao.DataAccessException;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;

/**
 *
 * @author Andrej Galád
 */
@UrlBinding("/users/{$event}/{user.id}")
public class UsersActionBean implements ActionBean {
 
    private ActionBeanContext context;
    
    @ValidateNestedProperties(value = {
            @Validate(on = {"add"}, field = "username", required = true, minlength = 2, maxlength = 30),
			@Validate(on = {"save"}, field = "password", minlength = 2, maxlength = 30),
            @Validate(on = {"add"}, field = "password", required = true, minlength = 2, maxlength = 30),
            @Validate(on = {"add", "save"}, field = "client.firstName", required = true, minlength = 2, maxlength = 50),
            @Validate(on = {"add", "save"}, field = "client.lastName", required = true, minlength = 2, maxlength = 50),
            @Validate(on = {"add", "save"}, field = "client.contact.phone", required = true, mask = "\\d*", maxlength = 30),
            @Validate(on = {"add", "save"}, field = "client.contact.email", required = true, mask = "[\\w\\-\\.\\+]+@[a-zA-Z0-9\\.\\-]+\\.[a-zA-z]+", minlength = 6, maxlength = 50),
            @Validate(on = {"add", "save"}, field = "client.contact.address", required = true, maxlength = 30),
            @Validate(on = {"add", "save"}, field = "client.contact.city", required = true, minlength = 2, maxlength = 50)
    })
    private RegUserTO user;
    
    public RegUserTO getLogged() {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        String username = auth.getName();
        return userService.findUserByUsername(username);
    }

    public RegUserTO getUser() {
        return user;
    }

    public void setUser(RegUserTO user) {
        this.user = user;
    }
    
    @SpringBean
    private RegUserService userService;
    
    private CountryPicker countryPicker = new CountryPicker();

    public Set<String> getCountries() {
        return countryPicker.getCountriesName();
    }
    
    @Override
    public void setContext(ActionBeanContext context) {
        this.context = context;
    }

    @Override
    public ActionBeanContext getContext() {
        return context;
    }
    
    @DefaultHandler
    public Resolution userDetails() {
        return new ForwardResolution("/users/user.jsp");
    }
    
    public Resolution register() {
        return new ForwardResolution("/register.jsp");
    }
    
    public Resolution add() {
        try {
            userService.create(user);
            return new RedirectResolution("/index.jsp");
        } catch (DataAccessException e) {
            ValidationErrors errors = new ValidationErrors();
            errors.add( "user.username", new LocalizableError("validation.user.nameIsExisting") );
            getContext().setValidationErrors(errors);
            return getContext().getSourcePageResolution();
        }
    }
    
    @Before(stages = LifecycleStage.BindingAndValidation, on = {"edit"})
    public void loadUserFromDatabase() {
        String ids = context.getRequest().getParameter("user.id");
        if (ids == null) {
            return;
        }
		Long id = Long.parseLong(ids);
		if (!getLogged().getId().equals(id)) {
			throw new WebApplicationException(Response.Status.FORBIDDEN);
		}
        user = userService.get(id);
    }

    public Resolution edit() {
        return new ForwardResolution("/users/editUser.jsp");
    }

    public Resolution save() {
        String ids = context.getRequest().getParameter("user.id");
        if (ids == null) {
            return new RedirectResolution(this.getClass(), "details");
        }
		Long id = Long.parseLong(ids);
		if (!getLogged().getId().equals(id)) {
			throw new WebApplicationException(Response.Status.FORBIDDEN);
		}
        RegUserTO userTmp = userService.get(id);
        user.setUsername(userTmp.getUsername());
        if (user.getPassword() == null) {
                user.setPassword(userTmp.getPassword());
        }
        user.getClient().setId(userTmp.getClient().getId());
		
        userService.update(user);
        return new RedirectResolution(this.getClass(), "details");
    }
}

HotelBookingManagerWeb/src/main/webapp/client/client.jsp
<%@ page contentType="text/html; charset=utf-8" pageEncoding="utf-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>

<fmt:message var="pageTitle" key="client.pageTitle"/>
<s:layout-render name="/layout.jsp" title="${pageTitle}" pageInfo="client.jsp">
    <s:layout-component name="right_content">
        <s:useActionBean beanclass="cz.fi.muni.pa165.hotelbookingmanagerweb.ClientsActionBean" var="actionBean"/>

            <div class="content_right_section">
                    <div class="content_title_01"><fmt:message key="clientManagement"/></div>
                    <img src="${pageContext.request.contextPath}/images/templatemo_image_04.jpg" alt="image" />
                    <fmt:message key="clientManagementDescription"/>
                </div>

                <div class="cleaner_h40">&nbsp;</div>


                <div class="content_right_section">
                    <div class="content_title_02"><fmt:message key="allClients"/></div>
                    <c:choose>
                        <c:when test="${empty actionBean.clients}">
                            <p class="emptyDb"><fmt:message key="noClients"/></p>
                        </c:when>
                        <c:otherwise>
                            <table id="table">
                                <thead>
                                    <th><fmt:message key="id"/></th>
                                    <th><fmt:message key="client.firstName"/></th>
                                    <th><fmt:message key="client.lastName"/></th>
                                    <th><fmt:message key="client.phone"/></th>
                                    <th><fmt:message key="client.email"/></th>
                                    <th></th>
                                    <th></th>
                                </thead>
                                <c:forEach items="${actionBean.clients}" var="client">
                                    <tr class="main">
                                        <td>${client.id}</td>
                                        <td><c:out value="${client.firstName}"/></td>
                                        <td><c:out value="${client.lastName}"/></td>
                                        <td><c:out value="${client.contact.phone}"/></td>
                                        <td><c:out value="${client.contact.email}"/></td>
                                        <td><s:link beanclass="cz.fi.muni.pa165.hotelbookingmanagerweb.ClientsActionBean" event="edit"><s:param name="client.id" value="${client.id}"/><img src="${pageContext.request.contextPath}/images/edit_icon.png" alt="edit" /></s:link> </td>
                                        <td><s:link beanclass="cz.fi.muni.pa165.hotelbookingmanagerweb.ClientsActionBean" event="delete" class="delete"><s:param name="client.id" value="${client.id}"/><img src="${pageContext.request.contextPath}/images/remove_icon.png" alt="delete" /></s:link> </td>

                                    </tr>
                                    <tr class="info">
                                        <%@include file="clientInfo.jsp" %>
                                    </tr>
                                </c:forEach>
                            </table>
                        </c:otherwise>
                    </c:choose>
            </div>
    </s:layout-component>
</s:layout-render>

HotelBookingManagerWeb/src/main/webapp/client/clientInfo.jsp
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<td colspan="100%" class="description">
        <div class="description_div">
                <span class="description_span"><fmt:message key="client.address"/>:</span>
                <c:out value="${client.contact.address}"/>
        </div>
        <div class="description_div">
            <span class="description_span"><fmt:message key="client.city"/>:</span>
                <c:out value="${client.contact.city}"/>
        </div>
        <div class="description_div">
                <span class="description_span"><fmt:message key="client.country"/>:</span>
                <c:out value="${client.contact.country}"/>
        </div>
</td>

HotelBookingManagerWeb/src/main/webapp/client/editClient.jsp
<%--
    Document   : editClient
    Created on : Nov 24, 2012, 10:31:07 PM
    Author     : Andrej Galád
--%>

<%@ page contentType="text/html; charset=utf-8" pageEncoding="utf-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>

<fmt:message var="pageTitle" key="client.pageTitle"/>
<s:layout-render name="/layout.jsp" title= "${pageTitle}" pageInfo="client.jsp">
    <s:layout-component name="right_content">
       <s:useActionBean beanclass="cz.fi.muni.pa165.hotelbookingmanagerweb.ClientsActionBean" var="actionBean"/>

            <div class="content_right_section">
                <div class="content_title_02"><fmt:message key="changeClient"/></div>
                <p><fmt:message key="changeClientDescription"/></p>

                <div class="cleaner">&nbsp;</div>
            </div>

            <div class="cleaner_h40">&nbsp;</div>

            <s:form beanclass="cz.fi.muni.pa165.hotelbookingmanagerweb.ClientsActionBean">
                <div class="content_right_section">
                    <div class="content_title_03"><fmt:message key="attributesClient"/> ${actionBean.client.firstName} ${actionBean.client.lastName}: </div>

                        <s:hidden name="client.id"/>
                        <%@include file="formClient.jsp"%>
                        <div class="cleaner_h20">&nbsp;</div>

                    <div class="cleaner">&nbsp;</div>
                </div> <!-- end of editing -->

                <div class="content_right_2column_box">
                    <s:submit name="save"/>
                    <div class="cleaner_h10">&nbsp;</div>
                </div>

                <div class="content_right_2column_box">
                    <div class="rc_btn_02"/><s:link href="/clients/clientAll"><fmt:message key="clientAll"/></s:link></div>
                    <div class="cleaner_h10">&nbsp;</div>
                </div>
            </s:form>

    </s:layout-component>
</s:layout-render>

HotelBookingManagerWeb/src/main/webapp/client/errorClient.jsp
<%@ page contentType="text/html; charset=utf-8" pageEncoding="utf-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>

<fmt:message var="pageTitle" key="client.pageTitle"/>
<s:layout-render name="/layout.jsp" title="${pageTitle}" pageInfo="client.jsp">
    <s:layout-component name="right_content">
            <div class="content_right_section">

                    <div class="content_title_01"><fmt:message key="errorMessageHeader1"/></div>

                    <p><fmt:message key="errorMessageDescription"/></p>

                    <div class="cleaner_h10">&nbsp;</div>

                    <div class="content_title_03"><fmt:message key="errorMessageHeader2"/></div>
                    <fmt:message key="clientDeleteError"/>
            </div>                   
            <div class="cleaner_h20">&nbsp;</div>
            <div class="rc_btn_01"><s:link href="/client/client.jsp"><fmt:message key="backToClients"/></s:link></div>
    </s:layout-component>
</s:layout-render>

HotelBookingManagerWeb/src/main/webapp/client/formClient.jsp
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>

<s:errors/>
<div class="form_row">
        <s:label for="b1" name="client.firstName"/>
        <s:text id="b1" name="client.firstName"/>
</div>
<div class="form_row">
        <s:label for="b2" name="client.lastName"/>
        <s:text id="b2" name="client.lastName"/>
</div>
<div class="form_row">
        <s:label for="b3" name="client.phone"/>
        <s:text id="b3" name="client.contact.phone"/>
</div>
<div class="form_row">
        <s:label for="b4" name="client.email"/>
        <s:text id="b4" name="client.contact.email"/>
</div>
<div class="form_row">
        <s:label for="b5" name="client.address"/>
        <s:text id="b5" name="client.contact.address"/>
</div>
<div class="form_row">
        <s:label for="b6" name="client.city"/>
        <s:text id="b6" name="client.contact.city"/>
</div>
<div class="form_row">
        <s:label for="b7" name="client.country"/>
        <s:select name="client.contact.country">
                <s:options-collection collection="${actionBean.countries}" style="width:20px;" />
            </s:select>
</div>