HotelBookingManagerWeb/src/main/java/cz/fi/muni/pa165/hotelbookingmanagerweb/ReservationsActionBean.java
package cz.fi.muni.pa165.hotelbookingmanagerweb;

import cz.fi.muni.pa165.hotelbookingmanagerapi.service.*;
import cz.fi.muni.pa165.hotelbookingmanagerapi.transferobjects.*;
import java.text.DateFormat;
import java.text.DateFormatSymbols;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sourceforge.stripes.action.*;
import net.sourceforge.stripes.controller.LifecycleStage;
import net.sourceforge.stripes.integration.spring.SpringBean;
import net.sourceforge.stripes.validation.*;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;

/**
 *
 * @author Marian Rusnak
 */
@UrlBinding("/reservations/{$event}/{reservation.id}")
public class ReservationsActionBean implements ActionBean {

	private ActionBeanContext context;
	
	// service
	@SpringBean
	private ReservationService reservationService;
	@SpringBean
	private HotelService hotelService;
	@SpringBean
	private ClientService clientService;
	@SpringBean
	private RoomService roomService;
        @SpringBean
        private RegUserService userService;
	
	// DTO
	private ReservationTO reservation;
	@ValidateNestedProperties(value = {
		@Validate(on = "add", field = "id", required = true)
	})
	private ClientTO client;
	@ValidateNestedProperties(value = {
		@Validate(on = "add", field = "id", required = true)
	})
	private RoomTO room;
	@ValidateNestedProperties(value = {
		@Validate(on = {"createContinue", "add"}, field = "id", required = true)
	})
	private HotelTO hotel;
	
	// hepler fields
	private String months;
	private List<ReservationTO> reservations;
	private DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
	@Validate(on = {"createContinue", "add"}, required = true)
	private String from;
	@Validate(on = {"createContinue", "add"}, required = true)
	private String to;
	private Date dateFrom;
	private Date dateTo;

	@ValidationMethod(on = {"createContinue", "add"})
	public void validateFutureDates(ValidationErrors errors) {
		dateFrom = getDateFrom();
		dateTo = getDateTo();
		if (dateFrom == null || dateTo == null) {
			return;
		}
		if (dateFrom.before(new Date())) {
			errors.add("dateFrom", new LocalizableError("validation.date.future"));
		}
		if (dateTo.before(new Date())) {
			errors.add("dateTo", new LocalizableError("validation.date.future"));
		}
	}

	@ValidationMethod()
	public void validateDates(ValidationErrors errors) {
		dateFrom = getDateFrom();
		dateTo = getDateTo();
		if (dateFrom == null || dateTo == null) {
			return;
		}
		if (dateFrom.after(dateTo)) {
			errors.add("dates", new LocalizableError("validation.date.after"));
		}
	}

	public String getFrom() {
		return from;
	}

	public void setFrom(String from) {
		this.from = from;
	}

	public String getTo() {
		return to;
	}

	public void setTo(String to) {
		this.to = to;
	}

	public HotelTO getHotel() {
		return hotel;
	}

	public void setHotel(HotelTO hotel) {
		this.hotel = hotel;
	}

	public List<HotelTO> getHotels() {
		return hotelService.findAllHotels();
	}

	public List<ClientTO> getClients() {
		return clientService.findAllClients();
	}

	public List<RoomTO> getRooms() {
		return roomService.findVacantRooms(getDateFrom(), getDateTo(), hotel);
	}

	public String getMonths() {
		return months;
	}

	public void setMonths(String months) {
		this.months = months;
	}
	
	public List<ReservationTO> getReservations() {
		return reservations;
	}

	public void setReservations(List<ReservationTO> reservations) {
		this.reservations = reservations;
	}

	public ReservationTO getReservation() {
		return reservation;
	}

	public void setReservation(ReservationTO reservation) {
		this.reservation = reservation;
	}

	public ClientTO getClient() {
		return client;
	}

	public void setClient(ClientTO client) {
		this.client = client;
	}

	public RoomTO getRoom() {
		return room;
	}

	public void setRoom(RoomTO room) {
		this.room = room;
	}

	@Override
	public void setContext(ActionBeanContext context) {
		this.context = context;
	}

	@Override
	public ActionBeanContext getContext() {
		return context;
	}

	@Before(stages = LifecycleStage.ResolutionExecution)
	public void populateMonths() {
		String[] monthNames = (new DateFormatSymbols()).getMonths();
		StringBuilder months = new StringBuilder("[ ");
		for (int i = 0; i < 11; i++) {
			months.append('\'').append(monthNames[i]).append("', ");
		}
		months.append('\'').append(monthNames[11]).append("' ]");
		this.months = months.toString();
	}
	
	@DefaultHandler
	public Resolution all() {
            RegUserTO user = getLoggedUser();
            if (user == null) {
		if (from != null && !from.equals("") && to != null && !to.equals("")) {
			String hotelID = context.getRequest().getParameter("hotel.id");
			HotelTO hotel = null;
			if (hotelID != null) {
				hotel = hotelService.findHotel(Long.parseLong(hotelID));
			}
			if (hotel != null) {
				reservations = reservationService.findReservationsByDate(getDateFrom(), getDateTo(), hotel);
			} else {
				reservations = reservationService.findReservationsByDate(getDateFrom(), getDateTo());
			}
		} else {
			reservations = reservationService.findAllReservations();
		}
            } else {
                reservations = reservationService.findReservationsByClient(user.getClient());
            }

            return new ForwardResolution("/reservation/reservation.jsp");
	}

	private Date getDateFrom() {
		if (dateFrom != null) {
			return dateFrom;
		}
		try {
			from = context.getRequest().getParameter("from");
			if (from == null) {
				return null;
			}
			dateFrom = dateFormat.parse(from);
			return dateFrom;
		} catch (ParseException ex) {
			Logger.getLogger(ReservationsActionBean.class.getName()).log(Level.SEVERE, null, ex);
		}
		return null;
	}

	private Date getDateTo() {
		if (dateTo != null) {
			return dateTo;
		}
		try {
			to = context.getRequest().getParameter("to");
			if (to == null) {
				return null;
			}
			dateTo = dateFormat.parse(to);
			return dateTo;
		} catch (ParseException ex) {
			Logger.getLogger(ReservationsActionBean.class.getName()).log(Level.SEVERE, null, ex);
		}
		return null;
	}

	public Resolution chooseDate() {
		return new RedirectResolution(this.getClass(), "all");
	}

	public Resolution create() {
		return new ForwardResolution("/reservation/createStepOne.jsp");
	}

	@Before(stages = LifecycleStage.BindingAndValidation, on = {"createContinue", "add"})
	public void loadHotelFromDatabase() {
		String hotelID = context.getRequest().getParameter("hotel.id");
		if (hotelID == null) {
			return;
		}
		hotel = hotelService.findHotel(Long.parseLong(hotelID));
                RegUserTO user = getLoggedUser();
                if (user != null) {
                    client = user.getClient();
                }
	}

	public Resolution createContinue() {
		return new ForwardResolution("/reservation/createStepTwo.jsp");
	}
        
        public Resolution goBack() {
                return create();
        }

	@Before(stages = LifecycleStage.BindingAndValidation, on = {"add"})
	public void loadClientAndRoomFromDatabase() {
                RegUserTO user = getLoggedUser();
                if (user == null) {
                    String clientID = context.getRequest().getParameter("client.id");
                    if (clientID == null)
                        return;
                    client = clientService.findClient(Long.parseLong(clientID));
                } else {
                    client = user.getClient();
                }
		String roomID = context.getRequest().getParameter("room.id");
		dateFrom = getDateFrom();
		dateTo = getDateTo();
		if (roomID == null || dateFrom == null || dateTo == null) {
			return;
                }
		room = roomService.getRoom(Long.parseLong(roomID));

		reservation = new ReservationTO();
		reservation.setFromDate(dateFrom);
		reservation.setToDate(dateTo);
		reservation.setClient(client);
		reservation.setRoom(room);
		reservation.setPrice(room.getPricePerNight());
	}

	public Resolution add() {
		reservationService.createReservation(reservation);
		return new RedirectResolution(this.getClass(), "all");
	}

	@Before(stages = LifecycleStage.BindingAndValidation, on = {"delete"})
	public void loadReservationFromDatabase() {
		String ids = context.getRequest().getParameter("reservation.id");
		if (ids == null) {
			return;
		}
		reservation = reservationService.getReservation(Long.parseLong(ids));
	}

	public Resolution delete() {
		reservationService.deleteReservation(reservation);
		return new RedirectResolution(this.getClass(), "all");
	}
        
        private RegUserTO getLoggedUser() {
            Authentication auth = SecurityContextHolder.getContext().getAuthentication();
            for (GrantedAuthority authority : auth.getAuthorities()) {
                if (authority.getAuthority().equals("ROLE_ADMIN"))
                    return null;
            }
            String username = auth.getName();
            return userService.findUserByUsername(username);
        }
}

HotelBookingManagerWeb/src/main/webapp/reservation/createStepOne.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html; charset=utf-8" pageEncoding="utf-8" %>
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>

<fmt:message var="pageTitle" key="client.pageTitle"/>

<s:layout-render name="/layout.jsp" title="${pageTitle}" pageInfo="reservation.jsp">
	<s:useActionBean beanclass="cz.fi.muni.pa165.hotelbookingmanagerweb.ReservationsActionBean" var="actionBean"/>

    <s:layout-component name="right_content">

		<div class="content_right_section">
			<div class="content_title_01"><fmt:message key="reservationManagement"/></div>
			<s:link beanclass="cz.fi.muni.pa165.hotelbookingmanagerweb.ReservationsActionBean" event="all"><fmt:message key="backToReservation"/></s:link>
				<div class="cleaner_h20">&nbsp;</div>
			<s:form beanclass="cz.fi.muni.pa165.hotelbookingmanagerweb.ReservationsActionBean">
				<s:errors/>
				<div class="content_right_section">
                                        <p><fmt:message key="createReservationStepOneDescription"/></p>
					<%@include file="/../components/dateChoose.jsp" %>
					<div>
						<s:label for="hotel"><fmt:message key="hotel"/>:</s:label>
						</div>
						<div>
						<s:select id="hotel" name="hotel.id" size="10" style="width:400px; border-radius:5px;">
							<s:options-collection collection="${actionBean.hotels}" value="id" />
						</s:select>
					</div>
					<div class="cleaner_h20">&nbsp;</div>
				</div>
				<div class="content_right_section">
					<div class="cleaner_h20">&nbsp;</div>
					<s:submit name="createContinue"><fmt:message key="continue"/></s:submit>
						<div class="cleaner_h40">&nbsp;</div>
					</div>
			</s:form>
		</div>

    </s:layout-component>
</s:layout-render>

HotelBookingManagerWeb/src/main/webapp/reservation/createStepTwo.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html; charset=utf-8" pageEncoding="utf-8" %>
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>

<fmt:message var="pageTitle" key="client.pageTitle"/>

<s:layout-render name="/layout.jsp" title="${pageTitle}" pageInfo="reservation.jsp">
	<s:useActionBean beanclass="cz.fi.muni.pa165.hotelbookingmanagerweb.ReservationsActionBean" var="actionBean"/>

    <s:layout-component name="right_content">

		<div class="content_right_section">
			<div class="content_title_01"><fmt:message key="reservationManagement"/></div>
			<s:link beanclass="cz.fi.muni.pa165.hotelbookingmanagerweb.ReservationsActionBean" event="all"><fmt:message key="backToReservation"/></s:link>
				<div class="cleaner_h20">&nbsp;</div>
			</div>
		<s:form beanclass="cz.fi.muni.pa165.hotelbookingmanagerweb.ReservationsActionBean">
			
			<div class="content_right_section">
                            <p><sec:authorize access="hasRole('ROLE_ADMIN')"><fmt:message key="createReservationStepTwoDescription"/></sec:authorize><sec:authorize access="hasRole('ROLE_USER')"><fmt:message key="createReservationStepTwoDescriptionUser"/></sec:authorize></p>
				<s:hidden name="from" />
				<s:hidden name="to" />
				<s:hidden name="hotel.id" />
			</div>
                        <div class="cleaner_h20">&nbsp;</div>
                        <s:errors/>
                      <sec:authorize access="hasRole('ROLE_ADMIN')">
			<div class="content_right_2column_box">
				<s:label for="client" class="content_title_03"><fmt:message key="client"/>:</s:label>
				<s:select id="client" name="client.id" size="10" style="width:230px; border-radius:5px;">
					<s:options-collection collection="${actionBean.clients}" value="id"/>
				</s:select>
			</div>
                      </sec:authorize>
			<div class="content_right_2column_box">
				<s:label for="room" class="content_title_03"><fmt:message key="room"/>:</s:label>
				<s:select id="room" name="room.id" size="10" style="width:230px; border-radius:5px;">
					<s:options-collection collection="${actionBean.rooms}" value="id"/>
				</s:select>
				<div class="cleaner_h40">&nbsp;</div>
			</div>
                       <sec:authorize access="hasRole('ROLE_USER')">
                           <s:hidden name="client.id" />
                           <div class="cleaner_h10">&nbsp;</div>
                       </sec:authorize>
			<div class="content_right_2column_box">
				<s:submit name="add" />
					<div class="cleaner_h10">&nbsp;</div>
				</div>
				<div class="content_right_2column_box">
                                    <s:submit name="goBack" />
					<div class="cleaner_h10">&nbsp;</div>
				</div>
		</s:form>
    </s:layout-component>
</s:layout-render>

HotelBookingManagerWeb/src/main/webapp/reservation/reservation.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="f" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ page contentType="text/html; charset=utf-8" pageEncoding="utf-8" %>
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>

<f:message var="pageTitle" key="reservation.pageTitle"/>
<s:layout-render name="/layout.jsp" title="${pageTitle}" pageInfo="reservation.jsp">
    <sec:authorize access="hasRole('ROLE_ADMIN')">
	<s:useActionBean beanclass="cz.fi.muni.pa165.hotelbookingmanagerweb.ReservationsActionBean" var="actionBean"/>
	<s:layout-component name="left_content">

		<div class="content_left_section">
			<div class="content_title_01"><f:message key="selectDateInterval"/></div>

			<s:form beanclass="cz.fi.muni.pa165.hotelbookingmanagerweb.ReservationsActionBean">
				<s:errors />
				<%@include file="/../components/dateChoose.jsp" %>
				<div>
					<div>
						<s:label for="hotel" name="hotel"/>
					</div>
					<div>
						<s:select id="hotel" name="hotel.id">
							<option value="-1">- <f:message key="any"/> -</option>
							<s:options-collection collection="${actionBean.hotels}" value="id" label="name" />
						</s:select>
					</div>
				</div>
				<div class="cleaner_h20">&nbsp;</div>
				<s:submit name="all"><f:message key="submit"/></s:submit>
			</s:form>

			<div class="cleaner">&nbsp;</div>
		</div>

		<div class="cleaner_h30">&nbsp;</div>
		<div class="cleaner_horizontal_divider_01">&nbsp;</div>
		<div class="cleaner_h30">&nbsp;</div>

    </s:layout-component>
</sec:authorize>
    <s:layout-component name="right_content">

		<div class="content_right_section">
			<div class="content_title_01"><f:message key="reservationManagement"/></div>
			<img src="${pageContext.request.contextPath}/images/templatemo_image_04.jpg" alt="image" />
			<p><f:message key="reservationManagementDescription"/></p>
		</div>

		<div class="cleaner_h40">&nbsp;</div>

		<div class="content_right_section">
			<div class="content_title_02"><f:message key="newReservation"/></div>
                        <p><f:message key="addReservationButtonDescription"/></p>
			<div class="rc_btn_02"><s:link beanclass="cz.fi.muni.pa165.hotelbookingmanagerweb.ReservationsActionBean" event="create"><f:message key="create"/></s:link></div>
			</div>

			<div class="cleaner_h40">&nbsp;</div>


			<div class="content_right_section">
				<div class="content_title_02"><f:message key="reservations"/></div>

			<c:choose>
				<c:when test="${empty actionBean.reservations}">
					<p class="emptyDb"><f:message key="noReservations"/></p>
				</c:when>
				<c:otherwise>
					<table id="table">
						<thead>
						<th><f:message key="client"/></th>
						<th><f:message key="room"/></th>
						<th><f:message key="dateFrom"/></th>
						<th><f:message key="dateTo"/></th>
						<th></th>
						</thead>
						<c:forEach items="${actionBean.reservations}" var="reservation">
							<tr>
								<td>${reservation.client.firstName} ${reservation.client.lastName}</td>
								<td>${reservation.room.roomType} - ${reservation.room.hotel.name}</td>
								<td><f:formatDate type="date" dateStyle="LONG" value="${reservation.fromDate}" /></td>
								<td><f:formatDate type="date" dateStyle="LONG" value="${reservation.toDate}" /></td>
								<td><s:link beanclass="cz.fi.muni.pa165.hotelbookingmanagerweb.ReservationsActionBean" event="delete" class="delete"><s:param name="reservation.id" value="${reservation.id}"/><img src="${pageContext.request.contextPath}/images/remove_icon.png" alt="delete" /></s:link> </td>
								</tr>
						</c:forEach>
					</table>
				</c:otherwise>
			</c:choose>
		</div>
    </s:layout-component>
</s:layout-render>